// Code generated by "stringer -type=LoxValueType"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BOOLEAN-0]
	_ = x[NUMBER-1]
	_ = x[NIL-2]
	_ = x[STRING-3]
	_ = x[OBJECT-4]
	_ = x[FUNCTION-5]
	_ = x[TYPE-6]
}

const _LoxValueType_name = "BOOLEANNUMBERNILSTRINGOBJECTFUNCTIONTYPE"

var _LoxValueType_index = [...]uint8{0, 7, 13, 16, 22, 28, 36, 40}

func (i LoxValueType) String() string {
	if i >= LoxValueType(len(_LoxValueType_index)-1) {
		return "LoxValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LoxValueType_name[_LoxValueType_index[i]:_LoxValueType_index[i+1]]
}
