// Code generated by tools/expr_gen.py. DO NOT EDIT.

package ast

import "github.com/LucazFFz/lox/internal/token"

type Stmt interface {
    EvaluateStmt
    DebugPrint
    ResolvableStmt
}

type ExpressionStmt struct {
    Expr Expr;
}

type PrintStmt struct {
    Expr Expr;
}

type VarStmt struct {
    Name token.Token;
    Initializer Expr;
}

type BlockStmt struct {
    Statements[] Stmt
}

type IfStmt struct {
    Condition Expr;
    ThenBranch Stmt;
    ElseBranch Stmt;
}

type WhileStmt struct {
    Condition Expr;
    Body Stmt;
}

type BreakStmt struct {

}

type ReturnStmt struct {
    Expr Expr;
}

type CallStmt struct {
	Callee    Expr
	Paren     token.Token
	Arguments []Expr
}

type FunctionStmt struct {
	Name       token.Token
	Parameters []token.Token
	Body       []Stmt
}
