// Code generated by tools/expr_gen.py. DO NOT EDIT.

package ast

import "github.com/LucazFFz/lox/internal/token"

type Stmt interface {
    EvaluateStmt
}

type Expression struct {
    Expr Expr;
}

type Print struct {
    Expr Expr;
}

type Var struct {
    Name token.Token;
    Initializer Expr;
}

