// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WHITESPACE-0]
	_ = x[COMMENT-1]
	_ = x[EOF-2]
	_ = x[ERROR-3]
	_ = x[LEFT_PAREN-4]
	_ = x[RIGHT_PAREN-5]
	_ = x[LEFT_BRACE-6]
	_ = x[RIGHT_BRACE-7]
	_ = x[COMMA-8]
	_ = x[DOT-9]
	_ = x[PLUS-10]
	_ = x[MINUS-11]
	_ = x[SEMICOLON-12]
	_ = x[SLASH-13]
	_ = x[STAR-14]
	_ = x[BANG-15]
	_ = x[BANG_EQUAL-16]
	_ = x[EQUAL-17]
	_ = x[EQUAL_EQUAL-18]
	_ = x[GREATER-19]
	_ = x[GREATER_EQUAL-20]
	_ = x[LESS-21]
	_ = x[LESS_EQUAL-22]
	_ = x[COLON-23]
	_ = x[QUESTION-24]
	_ = x[IDENTIFIER-25]
	_ = x[STRING-26]
	_ = x[NUMBER-27]
	_ = x[AND-28]
	_ = x[CLASS-29]
	_ = x[ELSE-30]
	_ = x[FALSE-31]
	_ = x[FUN-32]
	_ = x[FOR-33]
	_ = x[IF-34]
	_ = x[NIL-35]
	_ = x[OR-36]
	_ = x[PRINT-37]
	_ = x[RETURN-38]
	_ = x[SUPER-39]
	_ = x[THIS-40]
	_ = x[TRUE-41]
	_ = x[VAR-42]
	_ = x[WHILE-43]
}

const _TokenType_name = "WHITESPACECOMMENTEOFERRORLEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACECOMMADOTPLUSMINUSSEMICOLONSLASHSTARBANGBANG_EQUALEQUALEQUAL_EQUALGREATERGREATER_EQUALLESSLESS_EQUALCOLONQUESTIONIDENTIFIERSTRINGNUMBERANDCLASSELSEFALSEFUNFORIFNILORPRINTRETURNSUPERTHISTRUEVARWHILE"

var _TokenType_index = [...]uint16{0, 10, 17, 20, 25, 35, 46, 56, 67, 72, 75, 79, 84, 93, 98, 102, 106, 116, 121, 132, 139, 152, 156, 166, 171, 179, 189, 195, 201, 204, 209, 213, 218, 221, 224, 226, 229, 231, 236, 242, 247, 251, 255, 258, 263}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
