// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WHITESPACE-0]
	_ = x[COMMENT-1]
	_ = x[EOF-2]
	_ = x[LEFT_PAREN-3]
	_ = x[RIGHT_PAREN-4]
	_ = x[LEFT_BRACE-5]
	_ = x[RIGHT_BRACE-6]
	_ = x[COMMA-7]
	_ = x[DOT-8]
	_ = x[PLUS-9]
	_ = x[MINUS-10]
	_ = x[SEMICOLON-11]
	_ = x[SLASH-12]
	_ = x[STAR-13]
	_ = x[BANG-14]
	_ = x[BANG_EQUAL-15]
	_ = x[EQUAL-16]
	_ = x[EQUAL_EQUAL-17]
	_ = x[GREATER-18]
	_ = x[GREATER_EQUAL-19]
	_ = x[LESS-20]
	_ = x[LESS_EQUAL-21]
	_ = x[IDENTIFIER-22]
	_ = x[STRING-23]
	_ = x[NUMBER-24]
	_ = x[AND-25]
	_ = x[CLASS-26]
	_ = x[ELSE-27]
	_ = x[FALSE-28]
	_ = x[FUN-29]
	_ = x[FOR-30]
	_ = x[IF-31]
	_ = x[NIL-32]
	_ = x[OR-33]
	_ = x[PRINT-34]
	_ = x[RETURN-35]
	_ = x[SUPER-36]
	_ = x[THIS-37]
	_ = x[TRUE-38]
	_ = x[VAR-39]
	_ = x[WHILE-40]
}

const _TokenType_name = "WHITESPACECOMMENTEOFLEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACECOMMADOTPLUSMINUSSEMICOLONSLASHSTARBANGBANG_EQUALEQUALEQUAL_EQUALGREATERGREATER_EQUALLESSLESS_EQUALIDENTIFIERSTRINGNUMBERANDCLASSELSEFALSEFUNFORIFNILORPRINTRETURNSUPERTHISTRUEVARWHILE"

var _TokenType_index = [...]uint8{0, 10, 17, 20, 30, 41, 51, 62, 67, 70, 74, 79, 88, 93, 97, 101, 111, 116, 127, 134, 147, 151, 161, 171, 177, 183, 186, 191, 195, 200, 203, 206, 208, 211, 213, 218, 224, 229, 233, 237, 240, 245}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
