// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WHITESPACE-0]
	_ = x[COMMENT-1]
	_ = x[EOF-2]
	_ = x[LEFT_PAREN-3]
	_ = x[RIGHT_PAREN-4]
	_ = x[LEFT_BRACE-5]
	_ = x[RIGHT_BRACE-6]
	_ = x[COMMA-7]
	_ = x[DOT-8]
	_ = x[PLUS-9]
	_ = x[MINUS-10]
	_ = x[SEMICOLON-11]
	_ = x[SLASH-12]
	_ = x[STAR-13]
	_ = x[BANG-14]
	_ = x[BANG_EQUAL-15]
	_ = x[EQUAL-16]
	_ = x[EQUAL_EQUAL-17]
	_ = x[GREATER-18]
	_ = x[GREATER_EQUAL-19]
	_ = x[LESS-20]
	_ = x[LESS_EQUAL-21]
	_ = x[COLON-22]
	_ = x[QUESTION-23]
	_ = x[IDENTIFIER-24]
	_ = x[STRING-25]
	_ = x[NUMBER-26]
	_ = x[AND-27]
	_ = x[CLASS-28]
	_ = x[ELSE-29]
	_ = x[FALSE-30]
	_ = x[FUN-31]
	_ = x[FOR-32]
	_ = x[IF-33]
	_ = x[NIL-34]
	_ = x[OR-35]
	_ = x[PRINT-36]
	_ = x[RETURN-37]
	_ = x[SUPER-38]
	_ = x[THIS-39]
	_ = x[TRUE-40]
	_ = x[VAR-41]
	_ = x[WHILE-42]
}

const _TokenType_name = "WHITESPACECOMMENTEOFLEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACECOMMADOTPLUSMINUSSEMICOLONSLASHSTARBANGBANG_EQUALEQUALEQUAL_EQUALGREATERGREATER_EQUALLESSLESS_EQUALCOLONQUESTIONIDENTIFIERSTRINGNUMBERANDCLASSELSEFALSEFUNFORIFNILORPRINTRETURNSUPERTHISTRUEVARWHILE"

var _TokenType_index = [...]uint16{0, 10, 17, 20, 30, 41, 51, 62, 67, 70, 74, 79, 88, 93, 97, 101, 111, 116, 127, 134, 147, 151, 161, 166, 174, 184, 190, 196, 199, 204, 208, 213, 216, 219, 221, 224, 226, 231, 237, 242, 246, 250, 253, 258}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
